name: Utils
version: '${project.version}'
main: com.jakehonea.tests.TestPlugin
api-version: 1.16
authors: [ Jatatto ]
website: https://github.com/Jatatto
softdepend:
  - PlaceholderAPI
commands:
  test:
